# autogenerated by txs
#include:adjcalc
#include:collectbox
#include:graphicx
\clipbox#S
\expandafter#S
\marginbox#S
\trimbox#S
\clipbox*#S
\marginbox*#S
\trimbox*#S
adjcalc.sty#S
collectbox.sty#S
graphicx.sty#S
tc-pdftex.def#S
